apple_id ""

primary_category "Social Networking"

price_tier 0

screenshots_path "./screenshots"
app_icon './AppIcon.png'
ratings_config_path "./ratings.json"
copyright "Ayan Yenbekbay"

app_review_information(
  first_name: "Ayan",
  last_name: "Yenbekbay",
  phone_number: "6126444413",
  email_address: "ayan.yenb@gmail.com"
)
automatic_release true

success do
  system("say 'Successfully submitted a new version.'")
end
